### ISSUE TITLE
preserve input leading/trailing whitespace from beginning and end in output

### ISSUE THREAD

**Issue by kevinlawler** [alerque/decasify#21] opened 2024-10-15 22:02 UTC
whitespace is dropped if it is at the beginning or end. this is undesirable if using `titlecase` say as a method or plugin in a text editor such as `vim`. please preserve whitespace at beginning and end. I might prefer this to be the default behavior, but perhaps it makes sense to instead add this functionality as a flag like `-w` or `--preserve-leading-trailing-whitespace` (the naming does not matter to me)

input `    f  g   `
expected `    F  G    `
actual `F  G`

or with visible spaces:
input `␣␣␣␣f␣␣g␣␣␣`
expected `␣␣␣␣F␣␣G␣␣␣`
actual `F␣␣G`

**Comment by alerque** [comment] 2024-10-15 22:08
Thanks for the report. I agree this would be a desirable fix. My initial use cases were always for sentence strings with no leading or trailing space, but obviously that limits it to some use cases and there are others that it would be good to preserve the space.

Closely related (but not quite the same) implementation wise is #3.

**Comment by alerque** [comment] 2024-10-17 18:52
This should be working according to your expectations is #23. I need to fiddle with the release tooling for the new plugin rockspec and some other regression testing before it will release, but this should be in the next release as default output.

I'm also considering *optionally* adding some variant to get the old trimmed and compressed results because in spite of being accidental the normalized results were useful in same cases, but I'm not quite sure what the most ergonomic API for that would look like. That also probably means since the default handling will change it will be marked as a breaking release (since to get the same behavior you'll need something different about the API call).

**Comment by alerque** [comment] 2024-10-17 18:53
> his is undesirable if using `titlecase` say as a method or plugin in a text editor such as `vim`

Are you using the editor plugin built into this repository?

**Comment by kevinlawler** [comment] 2024-10-17 19:00
I'm not. I'm not familiar with `rocks.nvim`. I don't use package managers for vim/nvim. I looked at the vim plugin and it didn't look drop in so I didn't use it.

**Comment by alerque** [comment] 2024-10-17 20:04
You don't need `rocks.nvim` or any other plugin manager for that matter, however you usually install your plugins should work for this repository with two prerequisites:

1. It is NeoVIM only (written in Lua not Vimscript)
2. It does depend on your system having the `decasify` Lua Rock available. You can do this manually with `luarocks install decasify` or configuring your plugin manager to supply the dependency (`rocks.nvim` is the only one that automatically detects the dependency, but others can be configured manually.

I should document that better.

Also I'd be happy to include a Vimscript alternative implementation too for the pure VIM folks out there, but I don't have the urge to write that bit myself. A plain VIM plugin might either pass things through the CLI or it could make use of the Python module.

**Closed** 2024-10-17 21:20 UTC
